# Generated by Django 4.2.1 on 2023-05-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_idx', models.IntegerField(unique=True)),
                ('main_level', models.IntegerField()),
                ('main_level_tag', models.CharField(max_length=100)),
                ('sub_level', models.IntegerField()),
                ('sub_level_tag', models.CharField(max_length=100)),
                ('problem_comment', models.CharField(max_length=2000)),
                ('input_comment', models.CharField(max_length=2000)),
                ('output_comment', models.CharField(max_length=2000)),
                ('sample_data', models.JSONField()),
                ('chatgpt_output_code', models.CharField(max_length=6000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_idx', models.IntegerField(unique=True)),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
    ]
