# Generated by Django 4.1.7 on 2023-06-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="back4Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_level", models.IntegerField()),
                ("main_level_tag", models.TextField()),
                ("sub_level", models.IntegerField()),
                ("sub_level_tag", models.TextField()),
                ("problem_idx", models.IntegerField()),
                ("problem_comment", models.TextField()),
                ("input_comment", models.TextField()),
                ("output_comment", models.TextField()),
                ("sample_data", models.TextField()),
                ("chatGPT_output_code", models.TextField()),
                ("hidden_test_case", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="userproblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.TextField()),
                ("number", models.IntegerField()),
                ("accuracy", models.TextField()),
                ("seen", models.TextField()),
                ("error_injection_code", models.TextField()),
                ("problem_id", models.IntegerField()),
            ],
        ),
    ]
